apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ferry-register
  name: ferry-register
  namespace: ferry-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: ferry-register
  name: ferry-register
  namespace: ferry-system
rules:
  - apiGroups:
      - traffic.ferryproxy.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ferry-register
  name: ferry-register
  namespace: ferry-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ferry-register
subjects:
  - kind: ServiceAccount
    name: ferry-register
    namespace: ferry-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: ferry-register
  name: ferry-register
  namespace: ferry-tunnel-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ferry-register
  name: ferry-register
  namespace: ferry-tunnel-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ferry-register
subjects:
  - kind: ServiceAccount
    name: ferry-register
    namespace: ferry-system
---
apiVersion: v1
kind: Service
metadata:
  name: ferry-register
  namespace: ferry-system
spec:
  ports:
    - name: http
      nodePort: 31080
      port: 31080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ferry-register
  sessionAffinity: None
  type: {{ .ServiceType }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ferry-register
  name: ferry-register
  namespace: ferry-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferry-register
  template:
    metadata:
      labels:
        app: ferry-register
    spec:
      containers:
      - image: {{ .Image }}
        imagePullPolicy: IfNotPresent
        name: register
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        env:
          - name: TUNNEL_ADDRESS
            value: {{ .TunnelAddress }}
          - name: PORT_MANAGER_SERVICE_URL
            value: "http://ferry-tunnel.ferry-tunnel-system:8080/ports"
      restartPolicy: Always
      serviceAccount: ferry-register
      serviceAccountName: ferry-register
