apiVersion: ferry.daocloud.io/v1alpha1
kind: ClusterInformation
metadata:
  name: ferry-cluster2
spec:
  kubeconfig: #<base64-encoded-kubeconfig-data:data-plane-cluster-2>
  domain:
    kind: Service
  egress:
    apiGroup: "networking.k8s.io/v1"
    kind: "Ingress"
    serviceName: "ingress-nginx-controller"
    serviceNamespace: "ingress-nginx"
    port: 80