apiVersion: ferry.zsm.io/v1alpha1
kind: FerryPolicy
metadata:
  name: ferry-test
spec:
  rules:
    - exports:
        - clusterName: ferry-cluster1
          match:
            labels:
              ferry.zsm.io/export: "true"

      imports:
        - clusterName: ferry-cluster2
          match:
            labels:
              ferry.zsm.io/export: "true"
