apiVersion: ferry.zsm.io/v1alpha1
kind: FerryPolicy
metadata:
  name: ferry-test
  namespace: ferry-system
spec:
  rules:
    - exports:
        - clusterName: cluster-0
          match:
            labels:
              app: "web-0"

      imports:
        - clusterName: cluster-1
        - clusterName: cluster-2

    - exports:
        - clusterName: cluster-1
          match:
            labels:
              app: "web-1"
        - clusterName: cluster-2
          match:
            labels:
              app: "web-2"

      imports:
        - clusterName: cluster-0


    - exports:
        - clusterName: cluster-0
          match:
            namespace: test
            name: web-0

      imports:
        - clusterName: cluster-1
          match:
            namespace: test
            name: web-0-0
        - clusterName: cluster-2
          match:
            namespace: test
            name: web-0-0

    - exports:
        - clusterName: cluster-1
          match:
            namespace: test
            name: web-1

      imports:
        - clusterName: cluster-0
          match:
            namespace: test
            name: web-1-1

    - exports:
        - clusterName: cluster-2
          match:
            namespace: test
            name: web-2

      imports:
        - clusterName: cluster-0
          match:
            namespace: test
            name: web-2-2

    - exports:
        - clusterName: cluster-2
          match:
            namespace: test
            name: web-2

      imports:
        - clusterName: cluster-1
          match:
            namespace: test
            name: web-2

    - exports:
        - clusterName: cluster-1
          match:
            namespace: test
            name: web-1

      imports:
        - clusterName: cluster-2
          match:
            namespace: test
            name: web-1
