apiVersion: ferry.zsm.io/v1alpha1
kind: FerryPolicy
metadata:
  name: ferry-test
  namespace: ferry-system
spec:
  rules:
    - exports:
        - clusterName: ferry-cluster0
          match:
            labels:
              app: "web-0"

      imports:
        - clusterName: ferry-cluster1

    - exports:
        - clusterName: ferry-cluster1
          match:
            labels:
              app: "web-1"

      imports:
        - clusterName: ferry-cluster0
