kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31087
        hostPort: 8082
        listenAddress: "0.0.0.0"
        protocol: tcp