apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: ferry-joiner
  name: ferry-tunnel-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ferry-joiner
  name: ferry-joiner
  namespace: ferry-tunnel-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: ferry-joiner
  name: ferry-joiner
  namespace: ferry-tunnel-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - serviceaccounts/token
  verbs:
    - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ferry-joiner
  name: ferry-joiner
  namespace: ferry-tunnel-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ferry-joiner
subjects:
- kind: ServiceAccount
  name: ferry-joiner
  namespace: ferry-tunnel-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ferry-joiner
  name: ferry-joiner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ferry-joiner
subjects:
- kind: ServiceAccount
  name: ferry-joiner
  namespace: ferry-tunnel-system
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: ferry-joiner
  name: ferry-joiner
  namespace: ferry-tunnel-system
spec:
  template:
    metadata:
      labels:
        app: ferry-joiner
    spec:
      containers:
      - env:
        - name: REGISTER_SERVICE_URL
          value: {{ .BaseURL }}
        - name: HUB_NAME
          value: {{ .HubName }}
        image: {{ .Image }}
        imagePullPolicy: IfNotPresent
        name: joiner
      restartPolicy: OnFailure
      serviceAccount: ferry-joiner
      serviceAccountName: ferry-joiner
