
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ferry.daocloud.io
  resources:
  - clusterinformations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ferry.daocloud.io
  resources:
  - clusterinformations/finalizers
  verbs:
  - update
- apiGroups:
  - ferry.daocloud.io
  resources:
  - clusterinformations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ferry.daocloud.io
  resources:
  - ferrypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ferry.daocloud.io
  resources:
  - ferrypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - ferry.daocloud.io
  resources:
  - ferrypolicies/status
  verbs:
  - get
  - patch
  - update
