apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ferry-tunnel
    tunnel.ferryproxy.io/service: enabled
  name: {{ .ImportName }}-service
  namespace: ferry-tunnel-system
data:
  export_hub_name: {{ .ExportHubName }}
  import_service_namespace: {{ .ImportNamespace }}
  import_service_name: {{ .ImportServiceName }}
  ports: |
    [
      {
        "name": "{{ .ImportName }}",
        "port": {{ .ExportPort }},
        "protocol": "TCP",
        "targetPort": {{ .BindPort }}
      }
    ]
{{ if .ExportTunnelHost }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ferry-tunnel
    tunnel.ferryproxy.io/rules: enabled
  name: {{ .ImportName }}-tunnel
  namespace: {{ .ImportNamespace }}
data:
  tunnel: |
    [
      {
        "bind": [
          "0.0.0.0:{{ .BindPort }}"
        ],
        "proxy": [
          "{{ .ExportHost }}:{{ .ExportPort }}",
          "ssh://{{ .ExportTunnelHost }}:{{ .ExportTunnelPort }}?identity_data={{ .ExportTunnelIdentity }}"
        ]
      }
    ]
{{ end }}
