apiVersion: v1
kind: Secret
metadata:
  annotations:
    ferry.zsm.io/ssh-key: default
  name: {{ .ClusterName }}
  namespace: ferry-system
type: ferry.zsm.io/ssh-key
data:
  identity: {{ .Identity }}
  authorized: {{ .Authorized }}
  hostkey: {{ .Hostkey }}
