apiVersion: v1
kind: Service
metadata:
  labels:
    traffic.ferry.zsm.io/exported-from-ports: '{{ .TargetPort }}'
    tunnel.ferry.zsm.io/service: inject
  name: {{ .ServiceName }}
  namespace: {{ .ServiceNamespace }}
spec:
  ports:
    - port: {{ .Port }}
      protocol: TCP
      targetPort: {{ .TargetPort }}
  type: ClusterIP
