apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ferry-tunnel
    tunnel.ferryproxy.io/config: service
  name: "{{ .ServiceName }}-service"
  namespace: ferry-tunnel-system
data:
  import_service_namespace: "{{ .ServiceNamespace }}"
  import_service_name: "{{ .ServiceName }}"
  ports: |
    [
      {
        "name": "",
        "port": {{ .Port }},
        "protocol": "TCP",
        "targetPort": {{ .TargetPort }}
      }
    ]
