apiVersion: v1
kind: Config
current-context: {{ .Name }}
clusters:
  - name: {{ .Name }}
    cluster:
      insecure-skip-tls-verify: true
      server: {{ .ApiserverAddress }}
contexts:
  - name: {{ .Name }}
    context:
      cluster: {{ .Name }}
      user: {{ .Name }}
users:
  - name: {{ .Name }}
    user:
      token: {{ .Token }}
