apiVersion: v1
kind: Secret
metadata:
  annotations:
    traffic.ferryproxy.io/ssh-key: default
  name: ferry-tunnel
  namespace: ferry-tunnel-system
type: traffic.ferryproxy.io/ssh-key
data:
  identity: {{ .Identity }}
  authorized: {{ .Authorized }}
  hostkey: {{ .Hostkey }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ferry-tunnel
    tunnel.ferryproxy.io/service: inject
  name: ferry-tunnel
  namespace: ferry-tunnel-system
data:
  tunnel: |
    [
      {
        "bind": [
          "ssh://0.0.0.0:31087?authenticate=true&authorized_data={{ .Authorized }}&hostkey_data={{ .Hostkey }}"
        ],
        "proxy": [
          "-"
        ]
      }
    ]
