apiVersion: v1
kind: Secret
metadata:
  annotations:
    traffic.ferryproxy.io/ssh-key: default
  name: ferry-tunnel
  namespace: ferry-tunnel-system
type: traffic.ferryproxy.io/ssh-key
data:
  identity: "{{ .Identity }}"
  authorized_keys: "{{ .Authorized }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ferry-tunnel
    tunnel.ferryproxy.io/config: rules
  name: ferry-tunnel
  namespace: ferry-tunnel-system
data:
  tunnel: |
    [
      {
        "bind": [
          "ssh://0.0.0.0:31087?authenticate=true&hostkey_file=/var/ferry/ssh/identity&home_dir=/var/ferry/home/&permissions_file_name=permissions.json"
        ],
        "proxy": [
          "-"
        ]
      }
    ]
