apiVersion: v1
kind: Secret
metadata:
  annotations:
    traffic.ferry.zsm.io/ssh-key: default
  name: {{ .DataPlaneName }}
  namespace: ferry-system
type: traffic.ferry.zsm.io/kubeconfig-key
data:
  kubeconfig: {{ .DataPlaneKubeconfig }}
---
apiVersion: traffic.ferry.zsm.io/v1alpha2
kind: Hub
metadata:
  name: {{ .DataPlaneName }}
  namespace: ferry-system
spec:
  gateway:
    reachable: {{ .DataPlaneReachable }}
    address: {{ .DataPlaneTunnelAddress }}

{{ with .DataPlaneReception }}
    reception:
{{ range . }}
      - hubName: {{ . }}
{{ end}}
{{ else }}
    reception: []
{{ end }}

{{ with .DataPlaneNavigation }}
    navigation:
{{ range . }}
      - hubName: {{ . }}
{{ end}}
{{ else }}
    navigation: []
{{ end }}

