apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferry-control
  namespace: ferry-tunnel-system
  labels:
    app: ferry-control
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ferry-control
  namespace: ferry-tunnel-system
  labels:
    app: ferry-control
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ferry-control
  namespace: ferry-tunnel-system
  labels:
    app: ferry-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ferry-control
subjects:
  - kind: ServiceAccount
    name: ferry-control
    namespace: ferry-tunnel-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ferry-control
  labels:
    app: ferry-control
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ferry-control
  labels:
    app: ferry-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ferry-control
subjects:
  - kind: ServiceAccount
    name: ferry-control
    namespace: ferry-tunnel-system
---