apiVersion: v1
kind: Secret
metadata:
  annotations:
    traffic.ferryproxy.io/ssh-key: default
  name: {{ .DataPlaneName }}
  namespace: ferry-system
type: traffic.ferryproxy.io/kubeconfig-key
data:
  kubeconfig: {{ .DataPlaneKubeconfig }}
---
apiVersion: traffic.ferryproxy.io/v1alpha2
kind: Hub
metadata:
  name: {{ .DataPlaneName }}
  namespace: ferry-system
spec:
  gateway:
    reachable: {{ .DataPlaneReachable }}
    address: {{ .DataPlaneTunnelAddress }}

  {{ with .DataPlaneReceptionWay }}
    receptionWay:
  {{ range . }}
      - hubName: {{ . }}
  {{ end}}
  {{ else }}
    receptionWay: []
  {{ end }}

  {{ with .DataPlaneNavigationWay }}
    navigationWay:
  {{ range . }}
      - hubName: {{ . }}
  {{ end}}
  {{ else }}
    navigationWay: []
  {{ end }}


  {{ with .DataPlaneReceptionProxy }}
    receptionProxy:
  {{ range . }}
      - proxy: {{ . }}
  {{ end}}
  {{ else }}
    receptionProxy: []
  {{ end }}

  {{ with .DataPlaneNavigationProxy }}
    navigationProxy:
  {{ range . }}
      - hubName: {{ . }}
  {{ end}}
  {{ else }}
    navigationProxy: []
  {{ end }}

