name: e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pip3 install yq

    - name: Start cluster
      run: |
        ulimit -n 4096
        ./hack/clusters/up.sh
      env:
        IN_CLUSTER: "true"

    - name: Start controller
      run: ./test/run.sh

    - name: Test
      run: ./test/test-consistency.sh
