name: e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: pip3 install yq
    
    - name: Build
      run: go build ./cmd/controller

    - name: Start cluster
      run: |
        ulimit -n 4096
        ./hack/clusters/up.sh

    - name: Test
      run: |
        ./test/run.sh &
        sleep 20
        ./test/test.sh
