name: Ferryctl Binary

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build Cross Platform
      uses: wzshiming/action-go-build-cross-plantform@v1
      env:
        BASENAME: ferryctl
    - name: Upload Release Assets
      uses: wzshiming/action-upload-release-assets@v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
