name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - run: |
          go test ./pkg/...

  build-ferrctl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - run: |
        go build -o ferryctl ./cmd/ferryctl

    - name: Upload ferryctl
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: ferryctl

  build-ferry-controller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        docker build -t ferry-controller:test -f ./images/ferry-controller/Dockerfile . && docker save -o ferry-controller.tar ferry-controller:test

    - name: Upload ferry
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: ferry-controller.tar

  build-ferry-tunnel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        docker build -t ferry-tunnel:test -f ./images/ferry-tunnel/Dockerfile . && docker save -o ferry-tunnel.tar ferry-tunnel:test

    - name: Upload ferry-tunnel
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: ferry-tunnel.tar

  test-default:
    runs-on: ubuntu-latest
    needs:
    - build-ferrctl
    - build-ferry-controller
    - build-ferry-tunnel
    steps:
    - uses: actions/checkout@v3

    - name: Download for test
      uses: actions/download-artifact@v2
      with:
        name: test

    - name: Setup
      run: |
        cp ferryctl /usr/local/bin/ferryctl && chmod +x /usr/local/bin/ferryctl
        docker load -i ferry-controller.tar
        docker load -i ferry-tunnel.tar

    - name: Start cluster
      run: |
        ulimit -n 4096
        ./test/hack/start-environment.sh default

    - name: Test both
      run: ./test/test/test-both.sh

  test-reverse:
    runs-on: ubuntu-latest
    needs:
      - build-ferrctl
      - build-ferry-controller
      - build-ferry-tunnel
    steps:
      - uses: actions/checkout@v3

      - name: Download for test
        uses: actions/download-artifact@v2
        with:
          name: test

      - name: Setup
        run: |
          cp ferryctl /usr/local/bin/ferryctl && chmod +x /usr/local/bin/ferryctl
          docker load -i ferry-controller.tar
          docker load -i ferry-tunnel.tar

      - name: Start cluster
        run: |
          ulimit -n 4096
          ./test/hack/start-environment.sh reverse

      - name: Test both
        run: ./test/test/test-both.sh

  test-traversal:
    runs-on: ubuntu-latest
    needs:
    - build-ferrctl
    - build-ferry-controller
    - build-ferry-tunnel
    steps:
    - uses: actions/checkout@v3

    - name: Download for test
      uses: actions/download-artifact@v2
      with:
        name: test

    - name: Setup
      run: |
        cp ferryctl /usr/local/bin/ferryctl && chmod +x /usr/local/bin/ferryctl
        docker load -i ferry-controller.tar
        docker load -i ferry-tunnel.tar

    - name: Start cluster
      run: |
        ulimit -n 4096
        ./test/hack/start-environment.sh traversal

    - name: Test thrin
      run: ./test/test/test-thrin.sh

  test-forward:
    runs-on: ubuntu-latest
    needs:
    - build-ferrctl
    - build-ferry-tunnel
    steps:
      - uses: actions/checkout@v2

      - name: Download for test
        uses: actions/download-artifact@v2
        with:
          name: test

      - name: Setup
        run: |
          cp ferryctl /usr/local/bin/ferryctl && chmod +x /usr/local/bin/ferryctl
          docker load -i ferry-tunnel.tar

      - name: Start cluster
        run: |
          ulimit -n 4096
          ./test/hack/start-environment.sh forward

      - name: Test forward
        run: ./test/test/test-forward.sh

  test-manual:
    runs-on: ubuntu-latest
    needs:
      - build-ferrctl
      - build-ferry-tunnel
    steps:
      - uses: actions/checkout@v2

      - name: Download for test
        uses: actions/download-artifact@v2
        with:
          name: test

      - name: Setup
        run: |
          cp ferryctl /usr/local/bin/ferryctl && chmod +x /usr/local/bin/ferryctl
          docker load -i ferry-tunnel.tar

      - name: Start cluster
        run: |
          ulimit -n 4096
          ./test/hack/start-environment.sh manual

      - name: Test forward
        run: ./test/test/test-manual.sh
